### ISSUE TITLE
support for gitbucket 4.19

### ISSUE THREAD

**Issue by pgollor** [mrkm4ntr/gitbucket-network-plugin#11]
This plugins works successfully until gitbucket 4.18. But with 4.19.2 it doesn't.
Thanks a lot for the great work.

**Comment by pgollor** [comment]
Mybe the log could help:
```
main-gitbucket_1   | 17:04:09.009 [qtp424058530-11] ERROR gitbucket.core.plugin.PluginRegistry - Error during plugin initialization: gitbucket-network-plugin_2.12-1.4.jar
main-gitbucket_1   | java.lang.reflect.InvocationTargetException: null
main-gitbucket_1   | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
main-gitbucket_1   | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
main-gitbucket_1   | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
main-gitbucket_1   | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
main-gitbucket_1   | 	at gitbucket.core.plugin.PluginRegistry$.$anonfun$initialize$3(PluginRegistry.scala:275)
main-gitbucket_1   | 	at gitbucket.core.plugin.PluginRegistry$.$anonfun$initialize$3$adapted(PluginRegistry.scala:267)
main-gitbucket_1   | 	at scala.collection.immutable.List.foreach(List.scala:389)
main-gitbucket_1   | 	at gitbucket.core.plugin.PluginRegistry$.initialize(PluginRegistry.scala:267)
main-gitbucket_1   | 	at gitbucket.core.plugin.PluginRegistry$.reload(PluginRegistry.scala:209)
main-gitbucket_1   | 	at gitbucket.core.controller.SystemSettingsControllerBase.$anonfun$$init$$15(SystemSettingsController.scala:222)
main-gitbucket_1   | 	at org.scalatra.ScalatraBase.liftAction(ScalatraBase.scala:280)
main-gitbucket_1   | 	at org.scalatra.ScalatraBase.$anonfun$invoke$1(ScalatraBase.scala:274)
main-gitbucket_1   | 	at org.scalatra.ApiFormats.withRouteMultiParams(ApiFormats.scala:178)
main-gitbucket_1   | 	at org.scalatra.ApiFormats.withRouteMultiParams$(ApiFormats.scala:164)
main-gitbucket_1   | 	at gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:33)
main-gitbucket_1   | 	at org.scalatra.ScalatraBase.invoke(ScalatraBase.scala:273)
main-gitbucket_1   | 	at org.scalatra.ScalatraBase.invoke$(ScalatraBase.scala:272)
main-gitbucket_1   | 	at gitbucket.core.controller.ControllerBase.org$scalatra$json$JsonSupport$$super$invoke(ControllerBase.scala:33)
main-gitbucket_1   | 	at org.scalatra.json.JsonSupport.$anonfun$invoke$1(JsonSupport.scala:88)
main-gitbucket_1   | 	at org.scalatra.ApiFormats.withRouteMultiParams(ApiFormats.scala:178)
main-gitbucket_1   | 	at org.scalatra.ApiFormats.withRouteMultiParams$(ApiFormats.scala:164)
main-gitbucket_1   | 	at gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:33)
main-gitbucket_1   | 	at org.scalatra.json.JsonSupport.invoke(JsonSupport.scala:82)
main-gitbucket_1   | 	at org.scalatra.json.JsonSupport.invoke$(JsonSupport.scala:81)
main-gitbucket_1   | 	at gitbucket.core.controller.ControllerBase.invoke(ControllerBase.scala:33)
main-gitbucket_1   | 	at org.scalatra.ScalatraBase.$anonfun$runRoutes$3(ScalatraBase.scala:248)
main-gitbucket_1   | 	at scala.Option.flatMap(Option.scala:171)
main-gitbucket_1   | 	at org.scalatra.ScalatraBase.$anonfun$runRoutes$1(ScalatraBase.scala:246)
main-gitbucket_1   | 	at scala.collection.immutable.Stream.flatMap(Stream.scala:490)
main-gitbucket_1   | 	at org.scalatra.ScalatraBase.runRoutes(ScalatraBase.scala:245)
main-gitbucket_1   | 	at org.scalatra.ScalatraBase.runRoutes$(ScalatraBase.scala:243)
main-gitbucket_1   | 	at gitbucket.core.controller.ControllerBase.runRoutes(ControllerBase.scala:33)
main-gitbucket_1   | 	at org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:169)
main-gitbucket_1   | 	at org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:181)
main-gitbucket_1   | 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
main-gitbucket_1   | 	at org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:199)
main-gitbucket_1   | 	at org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:181)
main-gitbucket_1   | 	at org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:150)
main-gitbucket_1   | 	at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:33)
main-gitbucket_1   | 	at org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:123)
main-gitbucket_1   | 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
main-gitbucket_1   | 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
main-gitbucket_1   | 	at org.scalatra.DynamicScope.withResponse(DynamicScope.scala:79)
main-gitbucket_1   | 	at org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:77)
main-gitbucket_1   | 	at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:33)
main-gitbucket_1   | 	at org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:59)
main-gitbucket_1   | 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
main-gitbucket_1   | 	at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
main-gitbucket_1   | 	at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
main-gitbucket_1   | 	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:33)
main-gitbucket_1   | 	at org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:58)
main-gitbucket_1   | 	at org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:56)
main-gitbucket_1   | 	at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:33)
main-gitbucket_1   | 	at org.scalatra.ScalatraBase.handle(ScalatraBase.scala:123)
main-gitbucket_1   | 	at org.scalatra.ScalatraBase.handle$(ScalatraBase.scala:119)
main-gitbucket_1   | 	at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:33)
main-gitbucket_1   | 	at org.scalatra.servlet.ServletBase.handle(ServletBase.scala:53)
main-gitbucket_1   | 	at org.scalatra.servlet.ServletBase.handle$(ServletBase.scala:46)
main-gitbucket_1   | 	at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:33)
main-gitbucket_1   | 	at org.scalatra.FlashMapSupport.$anonfun$handle$1(FlashMap.scala:170)
main-gitbucket_1   | 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
main-gitbucket_1   | 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
main-gitbucket_1   | 	at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
main-gitbucket_1   | 	at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
main-gitbucket_1   | 	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:33)
main-gitbucket_1   | 	at org.scalatra.FlashMapSupport.handle(FlashMap.scala:145)
main-gitbucket_1   | 	at org.scalatra.FlashMapSupport.handle$(FlashMap.scala:144)
main-gitbucket_1   | 	at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:33)
main-gitbucket_1   | 	at org.scalatra.ScalatraFilter.$anonfun$doFilter$1(ScalatraFilter.scala:41)
main-gitbucket_1   | 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
main-gitbucket_1   | 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
main-gitbucket_1   | 	at org.scalatra.ScalatraFilter.doFilter(ScalatraFilter.scala:41)
main-gitbucket_1   | 	at org.scalatra.ScalatraFilter.doFilter$(ScalatraFilter.scala:36)
main-gitbucket_1   | 	at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:72)
main-gitbucket_1   | 	at gitbucket.core.servlet.CompositeScalatraFilter.$anonfun$doFilter$2(CompositeScalatraFilter.scala:46)
main-gitbucket_1   | 	at gitbucket.core.servlet.CompositeScalatraFilter.$anonfun$doFilter$2$adapted(CompositeScalatraFilter.scala:44)
main-gitbucket_1   | 	at scala.collection.immutable.List.foreach(List.scala:389)
main-gitbucket_1   | 	at scala.collection.generic.TraversableForwarder.foreach(TraversableForwarder.scala:35)
main-gitbucket_1   | 	at scala.collection.generic.TraversableForwarder.foreach$(TraversableForwarder.scala:35)
main-gitbucket_1   | 	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:44)
main-gitbucket_1   | 	at gitbucket.core.servlet.CompositeScalatraFilter.doFilter(CompositeScalatraFilter.scala:44)
main-gitbucket_1   | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
main-gitbucket_1   | 	at gitbucket.core.servlet.PluginControllerFilter.doFilter(PluginControllerFilter.scala:44)
main-gitbucket_1   | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
main-gitbucket_1   | 	at org.scalatra.ScalatraFilter.$anonfun$doNotFound$1(ScalatraFilter.scala:79)
main-gitbucket_1   | 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
main-gitbucket_1   | 	at org.scalatra.ScalatraBase.$anonfun$executeRoutes$5(ScalatraBase.scala:172)
main-gitbucket_1   | 	at scala.Option.getOrElse(Option.scala:121)
main-gitbucket_1   | 	at org.scalatra.ScalatraBase.$anonfun$executeRoutes$3(ScalatraBase.scala:172)
main-gitbucket_1   | 	at scala.Option.getOrElse(Option.scala:121)
main-gitbucket_1   | 	at org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:172)
main-gitbucket_1   | 	at org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:181)
main-gitbucket_1   | 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
main-gitbucket_1   | 	at org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:199)
main-gitbucket_1   | 	at org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:181)
main-gitbucket_1   | 	at org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:150)
main-gitbucket_1   | 	at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:33)
main-gitbucket_1   | 	at org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:123)
main-gitbucket_1   | 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
main-gitbucket_1   | 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
main-gitbucket_1   | 	at org.scalatra.DynamicScope.withResponse(DynamicScope.scala:79)
main-gitbucket_1   | 	at org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:77)
main-gitbucket_1   | 	at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:33)
main-gitbucket_1   | 	at org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:59)
main-gitbucket_1   | 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
main-gitbucket_1   | 	at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
main-gitbucket_1   | 	at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
main-gitbucket_1   | 	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:33)
main-gitbucket_1   | 	at org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:58)
main-gitbucket_1   | 	at org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:56)
main-gitbucket_1   | 	at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:33)
main-gitbucket_1   | 	at org.scalatra.ScalatraBase.handle(ScalatraBase.scala:123)
main-gitbucket_1   | 	at org.scalatra.ScalatraBase.handle$(ScalatraBase.scala:119)
main-gitbucket_1   | 	at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:33)
main-gitbucket_1   | 	at org.scalatra.servlet.ServletBase.handle(ServletBase.scala:53)
main-gitbucket_1   | 	at org.scalatra.servlet.ServletBase.handle$(ServletBase.scala:46)
main-gitbucket_1   | 	at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:33)
main-gitbucket_1   | 	at org.scalatra.FlashMapSupport.$anonfun$handle$1(FlashMap.scala:170)
main-gitbucket_1   | 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
main-gitbucket_1   | 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
main-gitbucket_1   | 	at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
main-gitbucket_1   | 	at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
main-gitbucket_1   | 	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:33)
main-gitbucket_1   | 	at org.scalatra.FlashMapSupport.handle(FlashMap.scala:145)
main-gitbucket_1   | 	at org.scalatra.FlashMapSupport.handle$(FlashMap.scala:144)
main-gitbucket_1   | 	at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:33)
main-gitbucket_1   | 	at org.scalatra.ScalatraFilter.$anonfun$doFilter$1(ScalatraFilter.scala:41)
main-gitbucket_1   | 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
main-gitbucket_1   | 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
main-gitbucket_1   | 	at org.scalatra.ScalatraFilter.doFilter(ScalatraFilter.scala:41)
main-gitbucket_1   | 	at org.scalatra.ScalatraFilter.doFilter$(ScalatraFilter.scala:36)
main-gitbucket_1   | 	at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:72)
main-gitbucket_1   | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
main-gitbucket_1   | 	at gitbucket.core.servlet.TransactionFilter.$anonfun$doFilter$1(TransactionFilter.scala:39)
main-gitbucket_1   | 	at gitbucket.core.servlet.TransactionFilter.$anonfun$doFilter$1$adapted(TransactionFilter.scala:30)
main-gitbucket_1   | 	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$2(BlockingProfile.scala:207)
main-gitbucket_1   | 	at slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(TransactionalJdbcBackend.scala:26)
main-gitbucket_1   | 	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$1(BlockingProfile.scala:207)
main-gitbucket_1   | 	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withSession(BlockingProfile.scala:200)
main-gitbucket_1   | 	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withTransaction(BlockingProfile.scala:207)
main-gitbucket_1   | 	at gitbucket.core.servlet.TransactionFilter.doFilter(TransactionFilter.scala:30)
main-gitbucket_1   | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1629)
main-gitbucket_1   | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
main-gitbucket_1   | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
main-gitbucket_1   | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
main-gitbucket_1   | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
main-gitbucket_1   | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
main-gitbucket_1   | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
main-gitbucket_1   | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
main-gitbucket_1   | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
main-gitbucket_1   | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
main-gitbucket_1   | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
main-gitbucket_1   | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
main-gitbucket_1   | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
main-gitbucket_1   | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
main-gitbucket_1   | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
main-gitbucket_1   | 	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
main-gitbucket_1   | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
main-gitbucket_1   | 	at org.eclipse.jetty.server.Server.handle(Server.java:561)
main-gitbucket_1   | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:334)
main-gitbucket_1   | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
main-gitbucket_1   | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
main-gitbucket_1   | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:104)
main-gitbucket_1   | 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
main-gitbucket_1   | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
main-gitbucket_1   | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
main-gitbucket_1   | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
main-gitbucket_1   | 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:243)
main-gitbucket_1   | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679)
main-gitbucket_1   | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597)
main-gitbucket_1   | 	at java.lang.Thread.run(Thread.java:748)
main-gitbucket_1   | Caused by: java.lang.NoClassDefFoundError: org/joda/time/ReadablePartial
main-gitbucket_1   | 	at Plugin.<init>(Plugin.scala:28)
main-gitbucket_1   | 	... 171 common frames omitted
main-gitbucket_1   | Caused by: java.lang.ClassNotFoundException: org.joda.time.ReadablePartial
main-gitbucket_1   | 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
main-gitbucket_1   | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
main-gitbucket_1   | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
main-gitbucket_1   | 	... 172 common frames omitted
```

**Comment by iTakeshi** [comment]
I tried to fix it by simply updating gitbucket version in dependencies, but couldn't get it work. Still same problem.
https://github.com/mrkm4ntr/gitbucket-network-plugin/compare/master...iTakeshi:gitbucket_4.19?expand=1

**Comment by source-c** [comment]
same issue here

**Comment by pgollor** [comment]
PR https://github.com/mrkm4ntr/gitbucket-network-plugin/pull/12 works for me

**Comment by source-c** [comment]
PR #12 works for me too

**Comment by mrkm4ntr** [comment]
Version 1.5 has released. Please try it :)

**Comment by pgollor** [comment]
Yepp it works. Many thanks.
